### PR TITLE
Fix queue cleanup in proposer

### LINKED ISSUE #91: Fix starting streaming since record boundary for safekeepers joining after voting

### PR DESCRIPTION
**Pull request by petuhovskiy**
There was a problem when `msgQueueHead` was moved further than `truncateLsn`, when `minQuorumLsn` matched end of wal record in the middle of queue message. When this happened, safekeeper started receiving WAL from the middle of WAL record and couldn't parse it.

This is fixed by splitting `truncateLsn` advancement and queue cleanup. Closes #91

### CODE REVIEW

File: src/backend/replication/walproposer.c [hunk 1]
```diff
@@ -383,17 +379,27 @@ HandleWalKeeperResponse(void)
...
 		{
 			truncateLsn = candidateTruncateLsn;
 			candidateTruncateLsn = InvalidXLogRecPtr;
 		}
+
+		msgQueueAck = msgQueueAck->next;
+	}
+
+	/* Cleanup message queue up to truncateLsn, but only messages received by everyone */
+	while (msgQueueHead != NULL && msgQueueHead->ackMask == ((1 << n_walkeepers) - 1) && msgQueueHead->req.endLsn <= truncateLsn)
```
Comment (arssher) [inline src/backend/replication/walproposer.c:398]: Isn't condition `msgQueueHead->ackMask == ((1 << n_walkeepers) - 1)` here unneccessary? Any chunk beyond truncateLsn must be already received by everyone.

Comment (petuhovskiy) [reply src/backend/replication/walproposer.c:398]: It is necessary. I also thought it's not needed, but it seems that code without it fails with 'Use After Free' error in the following case. A bunch of zero-length messages with `beginLsn == endLsn` are being broadcasted to the safekeepers, but not all of them are acknowledged back. After that `truncateLsn` is moved to this exact lsn and without this condition all empty messages are freed, but they're still not acked and used to retry sending.

Comment (arssher) [reply src/backend/replication/walproposer.c:398]: Oh, ok.
